### ISSUE TITLE
 Hey  I am getting "TypeError: Cannot read property 'publicKey' of undefined" on calling get request in NodeJS project.

### ISSUE THREAD

**Issue by Saifullahiub** [15Dkatz/cryptochain#3]
Full Error message is below..

```
C:\Users\Education Use\crypto\app\pubsub.js:66
                            inputAddress: this.wallet.publicKey
                                                      ^

TypeError: Cannot read property 'publicKey' of undefined
    at Object.message (C:\Users\Education Use\crypto\app\pubsub.js:66:55)
    at C:\Users\Education Use\crypto\node_modules\pubnub\lib\core\components\listener_manager.js:70:40
    at Array.forEach (<anonymous>)
    at _default.announceMessage (C:\Users\Education Use\crypto\node_modules\pubnub\lib\core\components\listener_manager.js:69:23)
    at C:\Users\Education Use\crypto\node_modules\pubnub\lib\core\components\subscription_manager.js:712:35
    at Array.forEach (<anonymous>)
    at _default._processSubscribeResponse (C:\Users\Education Use\crypto\node_modules\pubnub\lib\core\components\subscription_manager.js:579:16) 
    at onResponse (C:\Users\Education Use\crypto\node_modules\pubnub\lib\core\components\endpoint.js:252:7)
    at C:\Users\Education Use\crypto\node_modules\pubnub\lib\networking\modules\web-node.js:100:12
    at Request.callback (C:\Users\Education Use\crypto\node_modules\superagent\lib\node\index.js:716:12)
```

I am using PubNub Application and below is the pubsub.js file:

```
const PubNub = require('pubnub');

const credentials = {
    publishKey: 'pub-c-80cb1b82-bec3-46ec-bd1d-5ecfbdc7b268',
    subscribeKey: 'sub-c-9246a854-b768-11ea-bf7c-ae6a3e72d19d',
    secretKey: 'sec-c-YTA3ZmIwODYtNTI3Ni00ZWVkLWI0ZDYtMTlmY2QyNzM2Mzg0'
};

const CHANNELS = {
    TEST: 'TEST',
    BLOCKCHAIN: 'BLOCKCHAIN',
    TRANSACTION: 'TRANSACTION'
};

class PubSub{
    constructor({ blockchain, transactionPool }) {
        this.blockchain = blockchain;
        this.transactionPool = transactionPool;
        // this.wallet = wallet;
    
        this.pubnub = new PubNub(credentials);

        this.pubnub.subscribe({ channels: [Object.values(CHANNELS)] });

        this.pubnub.addListener(this.listener());
    }

    broadcastChain() {
        this.publish({
            channel: CHANNELS.BLOCKCHAIN,
            message: JSON.stringify(this.blockchain.chain)
        });
    }

    broadcastTransaction(transaction) {
        this.publish({
            channel: CHANNELS.TRANSACTION,
            message: JSON.stringify(transaction)
        });
    }

    subscribeToChannels() {
        this.pubnub.subscribe({
            channels: [Object.values(CHANNELS)]
        });
    }

    listener() {
        return {
            message: messageObject => {
                const { channel, message } = messageObject;
                
                console.log(`Message received. Channel: ${channel}. Message: ${message}`);
                const parsedMessage = JSON.parse(message);
                
                switch(channel) {
                    case CHANNELS.BLOCKCHAIN:
                        this.blockchain.replaceChain(parsedMessage, true, () => {
                            this.transactionPool.clearBlockchainTransactions(
                                { chain: parsedMessage.chain }
                            );
                        });
                        break;
                    case CHANNELS.TRANSACTION:
                        if (!this.transactionPool.existingTransaction({
                            inputAddress: this.wallet.publicKey
                        })) {
                            this.transactionPool.setTransaction(parsedMessage);
                        }
                        break;
                    default:
                        return;
                }
            }
        }
    }   
    
    publish({ channel, message }) {
    // there is an unsubscribe function in pubnub
    // but it doesn't have a callback that fires after success
    // therefore, redundant publishes to the same local subscriber will be accepted as noisy no-ops
    this.pubnub.publish({ message, channel });
    }

    broadcastChain() {
        this.publish({
            channel: CHANNELS.BLOCKCHAIN,
            message: JSON.stringify(this.blockchain.chain)
        });
    }
    
    broadcastTransaction(transaction) {
        this.publish({
            channel: CHANNELS.TRANSACTION,
            message: JSON.stringify(transaction)
        });
    }
}

module.exports = PubSub;

```
What can be the issue and how can I resolve this... please guide anyone.

**Comment by Saifullahiub** [comment]
Here is the index.js File

```
const bodyParser = require('body-parser');
const express = require('express');
const request = require('request');
//const path = require('path');
const Blockchain = require('./blockchain');
const PubSub = require('./app/pubsub');
const TransactionPool = require('./wallet/transaction-pool');
const Wallet = require('./wallet');

const app = express();
const blockchain = new Blockchain();
const transactionPool = new TransactionPool();
const wallet = new Wallet();
const pubsub = new PubSub({ blockchain, transactionPool });
//const transactionMiner = new TransactionMiner({ blockchain, transactionPool, wallet, pubsub });

const DEFAULT_PORT = 3000;
const ROOT_NODE_ADDRESS = `http://localhost:${DEFAULT_PORT}`;
 
app.use(bodyParser.json());

app.get('/api/blocks', (req, res) => {
    res.json(blockchain.chain);
});

app.post('/api/mine', (req, res) => {
    const { data } = req.body; 

    blockchain.addBlock({ data });
    
    pubsub.broadcastChain();
     
    res.redirect('/api/blocks');
});

app.post('/api/transact', (req, res) => {
    const { amount, recipient } = req.body;

    let transaction = transactionPool
        .existingTransaction({ inputAddress: wallet.publicKey });

    try {
        if (transaction) {
            transaction.update({ senderWallet: wallet, recipient, amount });
        } else {
            transaction = wallet.createTransaction({ recipient, amount });

        }
    } catch(error) {
        return res.status(400).json({ type: 'error', message: error.message });
    }

    transactionPool.setTransaction(transaction);

    pubsub.broadcastTransaction(transaction);

    console.log('transactionPool()', transactionPool);
  
    // let transaction = transactionPool
    //     .existingTransaction({ inputAddress: wallet.publicKey });
  
    res.json({ type: 'success', transaction });
});

app.get('/api/transaction-pool-map', (req, res) => {
    res.json(transactionPool.transactionMap);
});

const syncChains = ()=> {
    request({ url: `${ROOT_NODE_ADDRESS}/api/bocks` }, (error, response, body)=> {
        if (!error && response.statusCode === 200) {
            const rootChain = JSON.parse(body);
      
            console.log('replace transaction pool map on a sync with', rootChain);
            blockchain.replaceChain(rootChain);
        }
    });
} 

let PEER_PORT;

if (process.env.GENERATE_PEER_PORT === 'true') {
    PEER_PORT = DEFAULT_PORT + Math.ceil(Math.random() * 1000);
}

const PORT = PEER_PORT || DEFAULT_PORT;
app.listen(PORT, () => {
    console.log(`listening at localhost: ${PORT}`);

    if (PORT !== DEFAULT_PORT) {
        syncChains();
    }
});
```

when I try to send a get request using postman by following command
`
http://localhost:3000/api/transaction-pool-map
`
I got the above error.

**Comment by OisinHick** [comment]
How did you fix this?

**Comment by MikeBelyayaev** [comment]
> How did you fix this?

yeah. how?

**Comment by OisinHick** [comment]
Fixed this by removing the mine block endpoint. Once being able to send proper transactions is implemented mining blocks is apart of that process. Do not strobe the mine-blocks endpoint via postman was my fix
